name: scrollspyCI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: ["18.x", "19.0.0-rc.0"]
        node-version: [18.x, 22.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"

      - run: pnpm add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
